# Generated by Django 4.2 on 2023-04-18 00:13

from django.db import migrations, models
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Parceiro",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cnpj", models.CharField(max_length=14, unique=True)),
                ("razao_social", models.CharField(max_length=255)),
                (
                    "nome_fantasia",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "telefone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region=None
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("cep", models.CharField(max_length=8)),
                ("cidade", models.CharField(max_length=255)),
                ("estado", models.CharField(max_length=2)),
                ("endereco", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
