# Generated by Django 4.2 on 2023-04-18 02:11

import desafio_solfacil.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parceiro",
            name="cep",
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name="parceiro",
            name="cnpj",
            field=models.CharField(
                max_length=18,
                unique=True,
                validators=[
                    desafio_solfacil.core.validators.validate_cpf_or_cnpj
                ],
            ),
        ),
    ]
