FROM node:18 AS build

WORKDIR /html_app

COPY ./html_app/package*.json ./

RUN npm install

COPY html_app/ .

RUN npm run build

FROM nginx:1.19.0-alpine

COPY --from=build /html_app/build /usr/share/nginx/html

COPY html_app/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
