version: '3'

tasks:
  run:docker:
    desc: "Run program in docker"
    cmds:
      - docker-compose down --volumes
      - docker-compose build 
      - docker-compose up -d postgresql
      - docker-compose up web

  test:local:
    desc: "Run test locally"
    env:
      DATABASE_HOST: "localhost"
      DATABASE_PORT: "5431"
    cmds:
      - docker-compose down --volumes
      - docker-compose up -d postgresql
      - source .env.test
      - sleep 5
      - pytest tests/*