# Generated by Django 4.2 on 2023-04-30 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('razao_social', models.CharField(max_length=100)),
                ('nome_fantasia', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('cep', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=9)),
                ('logradouro', models.CharField(max_length=100)),
                ('complemento', models.CharField(max_length=100)),
                ('localidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('ibge', models.CharField(max_length=100)),
                ('gia', models.CharField(max_length=100)),
                ('ddd', models.CharField(max_length=3)),
                ('siafi', models.CharField(max_length=100)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.partner')),
            ],
        ),
    ]
