# Generated by Django 4.2 on 2023-04-17 20:14

import uuid
from typing import List

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: List = []

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cnpj", models.CharField(max_length=14, null=True)),
                ("cpf", models.CharField(max_length=11, null=True)),
                ("corporate_name", models.CharField(max_length=250)),
                ("trading_name", models.CharField(max_length=250, null=True)),
                ("phone", models.CharField(max_length=11, null=True)),
                ("email", models.CharField(max_length=250)),
                ("cep", models.CharField(max_length=8)),
                ("uf", models.CharField(max_length=2, null=True)),
                ("city", models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
