FROM python:3.10

WORKDIR /app

COPY requirements.txt ./requirements.txt

RUN pip3 install --no-cache-dir -r requirements.txt

EXPOSE 8000:8000

COPY . /app

CMD uvicorn main:app --reload --host 127.0.0.1 --port 8000
